import './globals.css'
import Navbar from "../component/Navbar/Navbar"
export const metadata = {
  title: 'Movies App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar />
      <body>{children}</body>
    </html>
  )
}
